### ISSUE TITLE
Problem with ghunit install, it provides a xcodeproj/ext (LoadError)

### ISSUE THREAD

**Issue by xplatsolutions** [gh-unit/gh-unit#169]
Hi,

When running the "ghunit install -n ProjectName" I get the following error.

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj/ext (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/ghunit-1.0.3/lib/ghunit/project.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/ghunit-1.0.3/lib/ghunit.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/ghunit-1.0.3/bin/ghunit:4:in `<top (required)>'
	from /usr/bin/ghunit:23:in `load'
	from /usr/bin/ghunit:23:in `<main>'

I have also tried to manually add a target, add the GHUnit.framework and run. It was working fine for a sample simple unit test until I needed to test my classes. So I added the headers, wrote some code and then it gave me undefined symbols.
Tried adding the cocoapod lib, Apple additional frameworks, almost what I use in my main project app target, nothing could overcome the issue.

**Comment by gabriel** [comment]
Ok I pushed a fix...

BTW, I created a fork which is a little more lightweight at https://github.com/gabriel/GRUnit

**Comment by gabriel** [comment]
and undefined symbols usually means you having included the source .m in your test target (that checkbox in the right panel)

**Comment by xplatsolutions** [comment]
Hi,

Thanks for the quick answer. GRUnit contains the fix, I will give it a try.

Hmmm, but I have added the .m files to the compile sources.

Cocoapods contain the fix or I have to download source and build the framework?

**Comment by gabriel** [comment]
re-install the gem... gem install ghunit

**Comment by xplatsolutions** [comment]
New one, just installed the gem again and run the command to install it in the project.

/Library/Ruby/Gems/2.0.0/gems/ghunit-1.0.5/bin/ghunit:18:in `block in <top (required)>': undefined method `banner' for main:Object (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/slop-4.0.0/lib/slop/options.rb:33:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/slop-4.0.0/lib/slop.rb:24:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/slop-4.0.0/lib/slop.rb:24:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/ghunit-1.0.5/bin/ghunit:17:in `<top (required)>'
	from /usr/bin/ghunit:23:in `load'
	from /usr/bin/ghunit:23:in `<main>'

**Comment by gabriel** [comment]
ok oops try again (after updating gem)

**Comment by xplatsolutions** [comment]
OK, it is installed properly and it looks you can run the sample test case.

Now Trying to bring my project's files to test them I get the undefined symbols again. Should I add my files to the compile sources of the Tests target?

**Comment by gabriel** [comment]
yeah... the ghunit command has a sync option to help with this  I think?
(or i added it to grunit)..

Try doing:

ghunit sync -n ProjectName

**Comment by xplatsolutions** [comment]
ghunit sync -n ProjectName didn't work but adding the files to the target did the job.
